ARGV <- commandArgs()

library(cummeRbund)

setwd(ARGV[6])

cuff=readCufflinks()
g=genes(cuff)
pdf("genes.dispersionPlot.pdf")
dispersionPlot(g)
dev.off()
pdf("genes.fpkmSCVPlot.pdf")
fpkmSCVPlot(g)
dev.off()
pdf("genes.csDensity.pdf")
csDensity(g)
dev.off()
pdf("genes.csBoxplot.pdf")
csBoxplot(g)
dev.off()
pdf("genes.csScatterMatrix.pdf")
csScatterMatrix(g)
dev.off()
pdf("genes.csDendro.pdf")
csDendro(g)
dev.off()
pdf("genes.csVolcanoMatrix.pdf")
csVolcanoMatrix(g)
dev.off()
pdf("genes.csDistHeat.pdf")
csDistHeat(g)
dev.off()
pdf("genes.PCAplot.pdf")
PCAplot(g,"PC1","PC2")
dev.off()

pdf("genes.csDensity.rep.pdf")
csDensity(g,replicates=T)
dev.off()
pdf("genes.csBoxplot.rep.pdf")
csBoxplot(g,replicates=T)
dev.off()
pdf("genes.csDendro.rep.pdf")
csDendro(g,replicates=T)
dev.off()
pdf("genes.csDistHeat.rep.pdf")
csDistHeat(g,replicates=T)
dev.off()
pdf("genes.PCAplot.rep.pdf")
PCAplot(g,"PC1","PC2",replicates=T)
dev.off()
pdf("genes.MDSplot.rep.pdf")
MDSplot(g,replicates=T)
dev.off()

pdf("genes.MDSplot.pdf")
MDSplot(g)
dev.off()




